[[plugins]]
repo = "Shougo/dein.vim"

# deoplete---------------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    call deoplete#custom#option({
    \ 'auto_complete_delay': 0,
    \ 'camel_case': 0,
    \ 'auto_complete_start_length': 1,
    \ 'ignore_case': 0,
    \ 'refresh_always': 0,
    \ 'smart_case': 1,
    \ 'max_list': 10000,
    \ })
    call deoplete#custom#var('file', 'enable_buffer_path', 1)
    set completeopt-=preview
'''

# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
    let g:neosnippet#snippets_directory='~/.dotfiles/nvim/snippets'
    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
    xmap <C-k>     <Plug>(neosnippet_expand_target)
'''
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'easymotion/vim-easymotion'

# append operator command
[[plugins]]
repo = 'tpope/vim-surround'

# bracket
[[plugins]]
repo = 'cohama/lexima.vim'

# nginx
[[plugins]]
repo = 'chr4/nginx.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rust-analyzer'],
    \ }
" note that if you are using Plug mapping you should not use `noremap` mappings.
" Or map each action separately
nmap <Leader>h <Plug>(lcn-hover)
nmap <Leader>gm <Plug>(lcn-menu)
nmap <Leader>f <Plug>(lcn-code-action)
nmap <Leader>gd :sp<CR><Plug>(lcn-definition)
nmap <Leader>gr :sp<CR><Plug>(lcn-references)
nmap <Leader>gi :sp<CR><Plug>(lcn-implementation)
'''

