[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'easymotion/vim-easymotion'

# open file from history
[[plugins]]
repo = 'Shougo/denite.nvim'

# Syntax and Language Snippet
[[plugins]]
repo = 'justmao945/vim-clang'
hook_add = '''
    let g:clang_c_options = '-std=c14'
    let g:clang_cpp_options = '-std=c++1z -stdlib=libstdc++ --pedantic-errors'
'''
on_ft = "*.c\(pp\)\?"


[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    let g:go_highlight_fields = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_types = 1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_function_arguments = 1
    let g:go_highlight_variable_declarations = 1
'''

# Syntax Highlight
## languages
[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'chr4/nginx.vim'

## Latex
[[plugins]]
repo = 'vim-latex/vim-latex'

# key value type files
[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = '*.toml'
